spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
logging:
  level:
    org.springframework.jms: INFO
    org.springframework.jms.listener.DefaultMessageListenerContainer: ERROR
    org.apache.activemq: INFO
    org.hibernate.SQL: INFO

