services:
  activemq:
    image: apache/activemq-artemis:latest-alpine
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
      # - "5672:5672"      # AMQP 1.0 (optional)
      # - "1883:1883"      # MQTT (optional)
      # - "61613:61613"    # STOMP (optional)
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
      - DISABLE_SECURITY=false
      # JAVA_ARGS: "-Xms512m -Xmx512m"     # tune heap; start small for dev
    volumes:
      - ../backend/db/activemq-data:/var/lib/artemis/data
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8161 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exampledb
    ports:
      - "54322:5432"
    volumes:
      - ../backend/db/postgresql:/var/lib/postgresql/data
      - ../backend/db/01-users.sql:/docker-entrypoint-initdb.d/01-users.sql
      - ../backend/db/02-db.sql:/docker-entrypoint-initdb.d/02-db.sql
      - ../backend/db/03-grants.sql:/docker-entrypoint-initdb.d/03-grants.sql
      - ../backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d exampledb || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
#volumes:
#  activemq-data:
#  pgdata:
