services:
  activemq:
    image: apache/activemq-artemis:latest-alpine
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
      # - "5672:5672"      # AMQP 1.0 (optional)
      # - "1883:1883"      # MQTT (optional)
      # - "61613:61613"    # STOMP (optional)
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
      - DISABLE_SECURITY=false
      # JAVA_ARGS: "-Xms512m -Xmx512m"     # tune heap; start small for dev
    volumes:
      - activemq-data:/var/lib/artemis/data
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8161 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  activemq-data:
