server:
  port: 9981
  shutdown: graceful
spring:
  application:
    name: notification-service
  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    cache:
      enabled: false
# JPA only if this app writes to DB (optional)
  jpa:
    open-in-view: false
  lifecycle:
    timeout-per-shutdown-phase: 30s

app:
  jms:
    shared:
      subscription_name: notif-shared
    mode: shared
# Logging
logging:
  level:
    org.springframework.jms: DEBUG